#!/bin/bash
#PBS -l ncpus=48
#PBS -l mem=2990GB
#PBS -l jobfs=1400GB
#PBS -q megamem
#PBS -P eg3
#PBS -l walltime=48:00:00
#PBS -l storage=gdata/hh5+gdata/dk92+gdata/ia39+scratch/eg3+gdata/xv83+gdata/mn51+gdata/xp65
#PBS -l wd
#PBS -j oe
#PBS -o logs


# module use /g/data/hh5/public/modules
# module load conda_concept/analysis3-23.04
# module load conda_concept/analysis3

module use /g/data/xp65/public/modules
module load conda/analysis3-25.06

module use /g/data/dk92/apps/Modules/modulefiles
module load gadi_jupyterlab/23.02

jupyter.ini.sh -D -p 52

command="python acs_run_qme.py ${gcm} ${empat} ${mdl_run} ${org} ${rcm} ${ref} ${var}"
echo ${command}
${command}
